FROM python:3.10-slim

WORKDIR /app

COPY frontend /app

RUN pip install streamlit requests blinker cachetools packaging tornado watchdog pillow protobuf tenacity toml gitpython pydeck numpy

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]
