FROM python:3.10-slim

WORKDIR /app

COPY backend/app /app/app
COPY backend/__init__.py /app/__init__.py

RUN pip install fastapi uvicorn

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
